export const API_HOME_DATA = './api/wangh_fxsc/category/lookCategory.Action'; //首页数据
export const API_HOME_POSITIONING_DATA = './api/wangh_fxsc/address/selCity.Action' // 首页地址数据
export const API_HOME_GOODS_DATA = './api/wangh_fxsc/goods/selGoods.Action' // 商品参数数据&&搜索
export const API_CLASS_class_CATEGORY_CATEGORY_DATA = './api/wangh_fxsc/category/selCategory.Action' // 分类数据
export const API_HOME_GOODS_EVALUATION_DATA = './api/wangh_fxsc/comment/selComment.Action' // 商品用户评价
export const API_LOGIN_REGISTERED_SMS_DATA = './api/wangh_fxsc/sms/sendSMS.Action' // 注册验证码
export const API_LOGIN_REGISTERED_DATA = './api/wangh_fxsc/login/registerLogin.Action' // 注册
export const API_LOGIN_DATA = './api/wangh_fxsc/login/login.Action' // 登录验证
export const API_LOGIN_SETFORGOTTEN_FORGET_SMS_DATA = './api/wangh_fxsc/sms/SMS.Action' // 忘记密码验证码
export const API_LOGIN_SETFORGOTTEN_FORGET_DATA = './api/wangh_fxsc/login/toEditLogin.Action' // 忘记密码
export const API_LOGIN_SETFORGOTTEN_MODIFY_DATA = './api/wangh_fxsc/login/EditLogin.Action' // 修改密码
export const API_HOME_HEADER_SEARCH_DATA = './api/wangh_fxsc/goods/selGoods.Action' // 头部商品搜索

export const API_HOME_CAR_GOODS_DATA = './api/wangh_fxsc/goods/selGoodsAttra.Action' // 具体商品购物车
export const API_HOME_CAR_ADD_DATA = './api/wangh_fxsc/shopCar/addShopCar.Action' // 添加到购物车
export const API_CAR_ORDER_DATA = './api/wangh_fxsc/shopCar/selShopCar.Action' // 查询购物车订单信息
export const API_CAR_ADDSHOPCARORDER_DATA = './api/wangh_fxsc/order/addShopCarOrder.Action' // 从购物车下订单
export const API_CAR_DELETE_DATA = './api/wangh_fxsc/shopCar/editShopCar.Action' // 删除购物车
export const API_CAR_PAY_DATA = './api/wangh_fxsc/ali/aliPay.Action' // 支付宝支付